scopes = ["esi-wallet.read_character_wallet.v1","esi-wallet.read_corporation_wallet.v1","esi-clones.read_clones.v1","esi-universe.read_structures.v1","esi-assets.read_assets.v1","esi-clones.read_implants.v1","esi-wallet.read_corporation_wallets.v1","esi-assets.read_corporation_assets.v1"]

import os

client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')

from http.server import HTTPServer
from functools import partial
import base64
import hashlib
import http.server
import json
import queue
import random
import requests
import secrets
import socketserver
import sqlite3
import subprocess
import ssl
import string
import threading
import time
import urllib
import yaml


from jose import jwt
from jose.exceptions import ExpiredSignatureError, JWTError

METADATA_URL = "https://login.eveonline.com/.well-known/oauth-authorization-server"
METADATA_CACHE_TIME = 300  # 5 minutes
ACCEPTED_ISSUERS = ("logineveonline.com", "https://login.eveonline.com")
EXPECTED_AUDIENCE = "EVE Online"

# We don't want to fetch the jwks data on every request, so we cache it for a short period
jwks_metadata = None
jwks_metadata_ttl = 0

callback_queue = queue.Queue()


def generate_code_challenge():
    """
    Generates a code challenge for PKCE.

    :returns: A tuple containing the code verifier and code challenge
    """
    code_verifier = base64.urlsafe_b64encode(secrets.token_bytes(32))
    sha256 = hashlib.sha256()
    sha256.update(code_verifier)
    code_challenge = base64.urlsafe_b64encode(sha256.digest()).decode().rstrip("=")
    return (code_verifier, code_challenge)


def request_token(authorization_code, code_verifier):
    """
    Takes an authorization code and code verifier and exchanges it for an access token and refresh token.

    :param str authorization_code: The authorization code received from the SSO
    :param str code_verifier: The code verifier used to generate the code challenge, as generated by `generate_code_challenge`
    :returns: A dictionary containing the access token and refresh token
    """
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    }
    payload = {
        "grant_type": "authorization_code",
        "code": authorization_code,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }
    response = requests.post(
        "https://login.eveonline.com/v2/oauth/token", headers=headers, data=payload
    )
    response.raise_for_status()

    return response.json()


def redirect_to_sso(scopes, redirect_uri, challenge):
    """
    Generates a URL to redirect the user to the SSO for authentication.

    :param list[str] scopes: A list of scopes that the application is requesting access to
    :param str redirect_uri: The URL where the user will be redirected back to after the authorization flow is complete
    :param str challenge: A challenge as generated by `generate_code_challenge`
    :returns: A tuple containing the URL and the state parameter that was used
    """
    state = "".join(random.choices(string.ascii_letters + string.digits, k=16))
    query_params = {
        "response_type": "code",
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "scope": " ".join(scopes),
        "state": state,
        "code_challenge": challenge,
        "code_challenge_method": "S256",
    }
    query_string = urllib.parse.urlencode(query_params)
    return (f"https://login.eveonline.com/v2/oauth/authorize?{query_string}", state)


def fetch_jwks_metadata():
    """
    Fetches the JWKS metadata from the SSO server.

    :returns: The JWKS metadata
    """
    global jwks_metadata, jwks_metadata_ttl
    if jwks_metadata is None or jwks_metadata_ttl < time.time():
        resp = requests.get(METADATA_URL)
        resp.raise_for_status()
        metadata = resp.json()

        jwks_uri = metadata["jwks_uri"]

        resp = requests.get(jwks_uri)
        resp.raise_for_status()

        jwks_metadata = resp.json()
        jwks_metadata_ttl = time.time() + METADATA_CACHE_TIME
    return jwks_metadata


def validate_jwt_token(token):
    """
    Validates a JWT Token.

    :param str token: The JWT token to validate
    :returns: The content of the validated JWT access token
    :raises ExpiredSignatureError: If the token has expired
    :raises JWTError: If the token is invalid
    """
    metadata = fetch_jwks_metadata()
    keys = metadata["keys"]
    # Fetch the key algorithm and key idfentifier from the token header
    header = jwt.get_unverified_header(token)
    key = [
        item
        for item in keys
        if item["kid"] == header["kid"] and item["alg"] == header["alg"]
    ].pop()
    return jwt.decode(
        token,
        key=key,
        algorithms=header["alg"],
        issuer=ACCEPTED_ISSUERS,
        audience=EXPECTED_AUDIENCE,
    )


def is_token_valid(token):
    """
    Simple check if the token is valid or not.

    :returns: True if the token is valid, False otherwise
    """
    try:
        claims = validate_jwt_token(token)
        # If our client_id is in the audience list, the token is valid, otherwise, we got a token for another client.
        return client_id in claims["aud"]
    except ExpiredSignatureError:
        # The token has expired
        return False
    except JWTError:
        # The token is invalid
        return False
    except Exception:
        # Something went wrong
        return False


# http://code.activestate.com/recipes/425210-simple-stoppable-server-using-socket-timeout/
class StoppableHTTPServer(HTTPServer):
    def server_bind(self):
        HTTPServer.server_bind(self)
        self.socket.settimeout(1)
        self.socket = ssl.wrap_socket(self.socket, certfile='/home/mitch/esi_shit/server.pem', server_side=True)
        self.run = True

    def get_request(self):
        while self.run:
            try:
                sock, addr = self.socket.accept()
                sock.settimeout(None)
                return sock, addr
            except:
                pass

    def stop(self):
        #print("server stop.")
        self.run = False

    def serve(self, callback=None):
        self.callback = callback
        while self.run:
            try:
                self.handle_request()
            except TypeError:
                print("Caught exception in serve")
                pass

        self.server_close()


class AuthHandler(http.server.BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()

    def do_GET(self):
        if self.path == "/favicon.ico":
            return
        parsed_path = urllib.parse.urlparse(self.path)
        parts = {k: ";".join(v) for k, v in urllib.parse.parse_qs(parsed_path.query).items()}
        #self.server.callback(parts)
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.server.stop()
        bound_f = partial(self.server.callback, parts)
        callback_queue.put(bound_f)

    def log_message(self, format, *args):
        return


def handleServerRequest(message):
    #print(message)
    print('auth successful...')
    auth_code = message['code']
    auth_state = message['state'] # unused?

    result = request_token(auth_code, code_verifier)
    jwt_tok = validate_jwt_token(result['access_token'])

    char_id = jwt_tok['sub'].split(':')[2]
    char_name = jwt_tok['name']
    print(f'Hello, {char_name} id #{char_id}')
    with open(f'char-{char_id}.txt', 'w') as cid:
        cid.write(char_name)
    headerz = {"Authorization": "Bearer {}".format(result['access_token'])}
    max_pages = 1
    curr_page = 1

    all_assets = []
    print(f'fetching assets page {curr_page} / ?...')
    while True:
        earl = f'https://esi.evetech.net/characters/{char_id}/assets?page={curr_page}'
        rez = requests.get(earl, headers=headerz)
        rez.raise_for_status()
        max_pages = int(rez.headers['X-Pages'], 10)
        all_assets.extend(rez.json())
        if max_pages == curr_page:
            break
        curr_page = curr_page + 1
        print(f'fetching assets page {curr_page} / {max_pages}...')
    print('done fetching assets.')

    locs = set()
    for item in all_assets:
        if item['location_flag'] == 'Hangar':
            locs.add(item['location_id'])
    
    stations = []
    structures = []
    for loc in locs:
        iloc = int(loc)
        if iloc >= 60000000 and iloc <= 64000000:
            stations.append(iloc)
        else:
            structures.append(iloc)
    
    print('fetching asset station info...')
    station_json = []
    with open(f'stations-{char_id}.json', 'w') as station_txt:
        for station in stations:
            earl = f'https://esi.evetech.net/universe/stations/{station}'
            rez = requests.get(earl, headers=headerz)
            rez.raise_for_status()
            jz = rez.json()
            # jz['id'] = station # already in there as station_id
            station_json.append(jz)
        station_txt.write(json.dumps(station_json))
    print('done.')

    print('fetching asset upwell structure info...')
    structure_json = []
    with open(f'structures-{char_id}.json', 'w') as structure_txt:
        for structure in structures:
            earl = f'https://esi.evetech.net/universe/structures/{structure}'
            rez = requests.get(earl, headers=headerz)
            rez.raise_for_status()
            jz = rez.json()
            jz['id'] = structure
            structure_json.append(jz)
        structure_txt.write(json.dumps(structure_json))
    print('done.')

    print('writing assets to file...')
    with open(f'assets-{char_id}.json', 'w') as text_file:
        text_file.write(json.dumps(all_assets))
    print('done.')

    singletons = []
    ships = []
    con = sqlite3.connect('sqlite-latest.sqlite')
    cur = con.cursor()

    print('calculating named items to fetch...')
    for item in all_assets:
        tid = item['type_id']
        if item['is_singleton']:
            #result = subprocess.run(['./jq.sh', f'{tid}'], stdout=subprocess.PIPE)
            #result.stdout.decode('utf-8')
            res = cur.execute(f'select 1 from invTypes it join invGroups ig on it.groupId=ig.groupId where ig.categoryID in (2,6) and it.typeId={tid};')
            #if result == '2' or result == '6':
            if res.fetchone() is not None:
                if len(singletons) < 1000:
                    singletons.append(item['item_id'])
                    if len(singletons) == 1000:
                        print('1k singletons reached')
                ships.append(item)
    con.close()
    ll = len(singletons)
    print(f'done. found {ll} named items.')

    print('fetching item names...')
    earl = f'https://esi.evetech.net/characters/{char_id}/assets/names'
    rez = requests.post(earl, headers=headerz, json=singletons)
    rez.raise_for_status()
    print('done.')
    print('writing item names to file...')
    with open(f'named_items-{char_id}.json', 'w') as named_items_txt:
        named_items_txt.write(json.dumps(rez.json()))
    print('done all asset fetching!')

httpd = StoppableHTTPServer(('localhost', 8088), AuthHandler)
serverThread = threading.Thread(target=httpd.serve, args=(handleServerRequest,))
serverThread.name = "SsoCallbackServer"
serverThread.daemon = True
serverThread.start()

chal = generate_code_challenge()
code_verifier = chal[0]
code_challenge = chal[1]
red_to_sso_res = redirect_to_sso(scopes, 'https://localhost:8088/evecallback', code_challenge)
url = red_to_sso_res[0]
state_param = red_to_sso_res[1]
print('open this and auth:')
print(url)
callback_queue.get()()
print('waiting for server thread to join...')
serverThread.join()
print('done. goodbye!')
